// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | BigTextSlice
  | AlternateTextSlice
  | CarouselSlice
  | SkydiveSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *AlternateText → Default → Primary → Text Group*
 */
export interface AlternateTextSliceDefaultPrimaryTextGroupItem {
  /**
   * Heading field in *AlternateText → Default → Primary → Text Group*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_text.default.primary.text_group[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *AlternateText → Default → Primary → Text Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_text.default.primary.text_group[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *AlternateText → Default → Primary*
 */
export interface AlternateTextSliceDefaultPrimary {
  /**
   * Text Group field in *AlternateText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_text.default.primary.text_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  text_group: prismic.GroupField<
    Simplify<AlternateTextSliceDefaultPrimaryTextGroupItem>
  >;
}

/**
 * Default variation for AlternateText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AlternateText*
 */
type AlternateTextSliceVariation = AlternateTextSliceDefault;

/**
 * AlternateText Shared Slice
 *
 * - **API ID**: `alternate_text`
 * - **Description**: AlternateText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateTextSlice = prismic.SharedSlice<
  "alternate_text",
  AlternateTextSliceVariation
>;

/**
 * Default variation for BigText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BigText*
 */
type BigTextSliceVariation = BigTextSliceDefault;

/**
 * BigText Shared Slice
 *
 * - **API ID**: `big_text`
 * - **Description**: BigText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigTextSlice = prismic.SharedSlice<
  "big_text",
  BigTextSliceVariation
>;

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Heading field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Price Copy field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.price_copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price_copy: prismic.RichTextField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Can image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.can_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  can_image: prismic.ImageField<never>;

  /**
   * second heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_heading: prismic.RichTextField;

  /**
   * second body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.second_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_body: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Skydive → Default → Primary*
 */
export interface SkydiveSliceDefaultPrimary {
  /**
   * sentence field in *Skydive → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skydive.default.primary.sentence
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sentence: prismic.KeyTextField;

  /**
   * Flavours field in *Skydive → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: lemonLime
   * - **API ID Path**: skydive.default.primary.flavours
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  flavours: prismic.SelectField<
    "lemonLime" | "grape" | "blackCherry" | "strawberryLemonade" | "watermelon",
    "filled"
  >;
}

/**
 * Default variation for Skydive Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkydiveSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkydiveSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Skydive*
 */
type SkydiveSliceVariation = SkydiveSliceDefault;

/**
 * Skydive Shared Slice
 *
 * - **API ID**: `skydive`
 * - **Description**: Skydive
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkydiveSlice = prismic.SharedSlice<
  "skydive",
  SkydiveSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateTextSlice,
      AlternateTextSliceDefaultPrimaryTextGroupItem,
      AlternateTextSliceDefaultPrimary,
      AlternateTextSliceVariation,
      AlternateTextSliceDefault,
      BigTextSlice,
      BigTextSliceVariation,
      BigTextSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SkydiveSlice,
      SkydiveSliceDefaultPrimary,
      SkydiveSliceVariation,
      SkydiveSliceDefault,
    };
  }
}
