// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_text: dynamic(() => import("./AlternateText")),
  big_text: dynamic(() => import("./BigText")),
  carousel: dynamic(() => import("./Carousel")),
  hero: dynamic(() => import("./Hero")),
  skydive: dynamic(() => import("./Skydive")),
};
